<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cups')->delete();
        
        \DB::table('cups')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Cowen Memorial Challenge Bowl',
                'prize_description' => 'A silver bowl and PHS certificate',
                'rules' => NULL,
                'image' => 'cowen_memorial_challenge_bowl.jpg',
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:31:57',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of greatest number of points for Flowers',
                'sort_order' => 10,
                'num_display_results' => 2,
                'section_id' => 2,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Clifford Bragg Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'clifford_bragg_cup.jpg',
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:32:28',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of greatest number of points in Fruit categories',
                'sort_order' => 20,
                'num_display_results' => 2,
                'section_id' => 3,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Petersham Perpetual Challenge Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'petersham_perpetual_challenge_cup.jpg',
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:32:50',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of greatest number of points in Vegetables and Produce',
                'sort_order' => 30,
                'num_display_results' => 2,
                'section_id' => 4,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'James Clark Memorial Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'james_clarke_memorial_cup.jpg',
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:33:10',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of greatest number of points in Floral Arrangement',
                'sort_order' => 40,
                'num_display_results' => 2,
                'section_id' => 5,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Philip Carr Challenge Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'phillip_carr_challenge_cup.jpg',
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:33:27',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of greatest number of points in Cookery',
                'sort_order' => 50,
                'num_display_results' => 2,
                'section_id' => 6,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Violet Lincoln Memorial Salver',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'Violet_lincoln_memorial_salver.jpg',
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:33:46',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of greatest number of points in Arts and Crafts',
                'sort_order' => 60,
                'num_display_results' => 2,
                'section_id' => 7,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Edmonds Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'edmonds_cup.jpg',
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:34:11',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of greatest number of points in Junior Arts and Crafts',
                'sort_order' => 70,
                'num_display_results' => 2,
                'section_id' => 9,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Pamela Griffiths Memorial Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'pamela_griffiths_memorial_cup.jpg',
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:36:58',
                'calculated_winner' => NULL,
                'winning_criteria' => 'Greatest number of points in Junior Floral',
                'sort_order' => 80,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Kathleen and Harold Sharp Trophy',
                'prize_description' => 'A silver trophy and PHS certificate',
                'rules' => NULL,
                'image' => 'kathleen_and_harold_sharp_trophy.jpg',
                'created_at' => NULL,
                'updated_at' => '2022-06-15 18:45:36',
                'calculated_winner' => NULL,
                'winning_criteria' => 'For the winner of "One vase of mixed Garden Flowers"',
                'sort_order' => 90,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Mary Turner Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'mary_turner_cup.jpg',
                'created_at' => NULL,
                'updated_at' => '2022-06-15 18:47:29',
                'calculated_winner' => NULL,
                'winning_criteria' => 'For the winner of the "Childrens fruit / Vegetable" Category',
                'sort_order' => 100,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'PHS Top Tray',
                'prize_description' => NULL,
            'rules' => '<ol><li>The Petersham Top Tray class is for a collection of three types of vegetables taken from the following list of fifteen. The quantity of each vegetable required for the collection is given in brackets: carrots (3), cauliflowers (2), onions (3), parsnips (3), peas (6 pods), potatoes (3), runner beans (6 pods), tomatoes (6), French Beans (6 pods), sweetcorn (2), pepper (3), cucumber (2), courgettes (3), red beet (3), aubergines (2). Each type of vegetable will be judged out of a total of 20 points. This is split into three sections as follows: 7 points for size, shape and colour; 7 points for condition; 6 points for uniformity. The overall mark will be out of a total of 60.</li><li>All vegetables are to be displayed for effect. The vegetables must be displayed within an area measuring 45cm by 60cm (18x24in), without bending any part of them. No part of any exhibit may exceed the size of the tray. A tray or board measuring 45cm by 60cm (18x24in) can be used to display the vegetables, or the area can simply be marked on the staging. Where a tray has a lip or edge, it is the internal measurements that must not exceed 45cm by 60cm (18x24in).</li><li>A black cloth is permitted, and the tray may be painted but not be cut in any way at all. Parsley is allowed for garnishing, but no other foliage or accessories, such as plates, sand, rings and so on, will be allowed. Onion tops may be tied or whipped using raffia or string. Carrots and parsnips must have foliage trimmed back to 7.5cm (3in). Peas and beans must be displayed with some stalk attached. Tomatoes must be displayed with calyces (the green flower bud case).</li></ol><div><br></div><div><br></div>',
                'image' => NULL,
                'created_at' => NULL,
                'updated_at' => '2024-06-18 21:28:30',
                'calculated_winner' => NULL,
                'winning_criteria' => 'Best in Top Tray category',
                'sort_order' => 110,
                'num_display_results' => 3,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'PHS Top Vase',
                'prize_description' => NULL,
            'rules' => '<ol><li>The Top Vase class is for a vase of mixed flowering stems containing a total of between 5 and 10, taken from a minimum of two different kinds of plants. Please note that it is two different KINDS of plants, two varieties of the same plant are NOT two kinds (e.g. Pinks and Sweet Williams are both Dianthus, so would not be classed as different kinds).</li><li>The display is judged out of a total of 35 points, split into: 25 points for the colour, form, condition, quality and freshness of the flowers on display, and 10 points for the overall presentation and effect of the flowers in the vase. The vase will be viewed from all directions. Judging of flowers should be to the normal rules used for other classes.</li><li>Stems used in the display must be showing flowers only; no seed heads or berries will be allowed.</li><li>The vase can be any shape and size and made from any material, but must be in proportion to the display. No marks are awarded for the vase itself.</li><li>No accessories such as bows and additional foliage will be allowed. Foliage which is growing naturally from the flowering stem, and still attached to that stem, is allowed. No dried or silk flowers allowed. Packing material – including florists’ foam – to keep the stems in place is allowed.&nbsp;</li></ol><div><br></div><div><br></div><div><br></div>',
                'image' => NULL,
                'created_at' => NULL,
                'updated_at' => '2024-06-18 21:32:57',
                'calculated_winner' => NULL,
                'winning_criteria' => 'Best in Top Vase',
                'sort_order' => 120,
                'num_display_results' => 3,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Banksian Medal',
                'prize_description' => 'An RHS Banksian Medal and an RHS certificate',
                'rules' => NULL,
                'image' => NULL,
                'created_at' => NULL,
                'updated_at' => '2024-06-08 15:41:33',
                'calculated_winner' => NULL,
            'winning_criteria' => 'The largest total amount of points in the whole of the horticultural classes at the Show, or who has the highest number of place points within the vegetable, fruit, flower and plant sections (Exclusions apply)',
                'sort_order' => 130,
                'num_display_results' => 4,
                'section_id' => NULL,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Anthony Rampton Memorial Prize',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'anthony_rampton_memorial_prize.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'Most meritorious photograph exhibit',
                'sort_order' => 140,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Cowen Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'cowen_cup.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'Most Meritorious Exhibit of Children\'s Art',
                'sort_order' => 150,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Best in Show Artwork Rosette',
                'prize_description' => 'A rosette and a PHS certificate',
                'rules' => NULL,
                'image' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'Best in show - Adult or Children\'s art',
                'sort_order' => 160,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'North Trophy',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'north_trophy.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'The cookery exhibit that gives the judge the most pleasure',
                'sort_order' => 170,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Harry Thorne Memorial Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'harry_thorne_memorial_cup.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'Most Meritorious exhibit of vegetables in the show',
                'sort_order' => 180,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            18 => 
            array (
                'id' => 24,
                'name' => 'Lambert Memorial Bowl & Worshipful Company of Gardener\'s Diploma of Excellence',
                'prize_description' => 'A silver cup and Worshipful Company of Gardeners Diploma',
                'rules' => NULL,
                'image' => 'lambert_memorial_bowl.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'Best entry for any rose in any category',
                'sort_order' => 240,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            19 => 
            array (
                'id' => 25,
                'name' => 'Anne Millard Cup',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'anne_millard_cup.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'Best Junior Floral',
                'sort_order' => 250,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            20 => 
            array (
                'id' => 26,
                'name' => 'John Grapes Memorial Trophy',
                'prize_description' => 'A silver cup and PHS certificate',
                'rules' => NULL,
                'image' => 'john_grapes_memorial_trophy.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'Most Meritorious Exhibit of Flowers in the show',
                'sort_order' => 260,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            21 => 
            array (
                'id' => 27,
            'name' => 'The Worshipful Company of Gardeners; Certificate of Merit (floral decoration)',
                'prize_description' => 'Worshipful Company of Gardeners certificate of Merit',
                'rules' => NULL,
                'image' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-06 19:46:25',
                'calculated_winner' => NULL,
                'winning_criteria' => 'Best Floral art entry',
                'sort_order' => 270,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            22 => 
            array (
                'id' => 28,
            'name' => 'RHS Certificate of Merit (Junior Floral, Fruit and Vegetables)',
                'prize_description' => 'An RHS certificate of merit',
                'rules' => NULL,
                'image' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'calculated_winner' => NULL,
                'winning_criteria' => 'Best Junior Floral, Fruit & Vegetable entry',
                'sort_order' => 280,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            23 => 
            array (
                'id' => 29,
                'name' => 'Col Bromhead Memorial Cup Rosette and Certificate',
                'prize_description' => 'A rosette and a PHS certificate',
                'rules' => NULL,
                'image' => 'col_bromhead_memorial_cup.jpg',
                'created_at' => NULL,
                'updated_at' => '2022-07-06 20:24:55',
                'calculated_winner' => NULL,
                'winning_criteria' => 'Best in Show in either fruit, flowers or vegetables',
                'sort_order' => 290,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'judges_choice',
                'judges_notes' => NULL,
            ),
            24 => 
            array (
                'id' => 30,
                'name' => 'The Worshipful Company of Gardeners’ Certificate of Merit in Horticulture',
                'prize_description' => 'A certificate from the Worshipful Company of Gardeners',
                'rules' => NULL,
                'image' => NULL,
                'created_at' => NULL,
                'updated_at' => '2024-06-09 08:25:32',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of greatest number of points in the Novice categories',
                'sort_order' => 1,
                'num_display_results' => 2,
                'section_id' => 1,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
            25 => 
            array (
                'id' => 31,
                'name' => 'Alf Gundry Memorial Prize',
                'prize_description' => 'A garden voucher and a PHS certificate',
                'rules' => NULL,
                'image' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-05-17 20:53:25',
                'calculated_winner' => NULL,
                'winning_criteria' => 'The winner of "A collection of mixed vegetables"',
                'sort_order' => 35,
                'num_display_results' => 2,
                'section_id' => NULL,
                'winning_basis' => 'total_points',
                'judges_notes' => NULL,
            ),
        ));
        
        
    }
}