<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SectionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sections')->delete();
        
        \DB::table('sections')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Novices',
                'number' => '1',
                'notes' => 'Entry to this novice class is open to members who have not won a prize in any previous Petersham Flower Show',
                'judges' => 'Mr R. Bailey & Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Flowers',
                'number' => '2',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => '<img class="alignleft size-full wp-image-62" title="Winning Rose" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/WinningRose.jpg" alt="A winning rose in our Flowers section" width="225" height="300">',
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Fruit',
                'number' => '3',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Vegetables & Produce',
                'number' => '4',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-63" title="judging vegetables" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/judging-vegetables.jpg" alt="Image of Mr Studman judging vegetables" width="200" height="300">',
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 2,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Floral Arrangement',
                'number' => '5',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => NULL,
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Cookery',
                'number' => '6',
                'notes' => NULL,
                'judges' => 'Mr J. Rounce',
                'image' => '<img class="alignleft size-full wp-image-64" title="cakes" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/cakes.jpg" alt="Some cakes waiting to be judged" width="202" height="134">',
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Arts & Crafts',
                'number' => '7',
                'notes' => NULL,
                'judges' => 'Mrs C. Tudway & Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-66" title="Cushion" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/Cushion.jpg" alt="A prize-winning cushion" width="200" height="300">',
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Floral, Fruit & Vegetables',
                'number' => '8',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey and Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-68" title="wildlife garden" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/wildlife-garden.jpg" alt="A junior wildlife garden" width="300" height="200">',
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Cookery, Arts & Crafts',
                'number' => '9',
                'notes' => NULL,
                'judges' => 'Mr Rounce, Mr Bailey, Mr Kimbell, Mrs Tudway, Mrs Edwards &  Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-70" title="junior cookery" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/junior-cookery.jpg" alt="Miscellaneous winning junior cookery prizes" width="300" height="200">',
                'show_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Novices',
                'number' => '1',
                'notes' => 'Entry to this novice class is open to members who have not won a prize in any previous Petersham Flower Show',
                'judges' => 'Mr R. Bailey & Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Flowers',
                'number' => '2',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => '<img class="alignleft size-full wp-image-62" title="Winning Rose" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/WinningRose.jpg" alt="A winning rose in our Flowers section" width="225" height="300">',
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Fruit',
                'number' => '3',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 3,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Vegetables & Produce',
                'number' => '4',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-63" title="judging vegetables" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/judging-vegetables.jpg" alt="Image of Mr Studman judging vegetables" width="200" height="300">',
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Floral Arrangement',
                'number' => '5',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => NULL,
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 5,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Cookery',
                'number' => '6',
                'notes' => NULL,
                'judges' => 'Mr J. Rounce',
                'image' => '<img class="alignleft size-full wp-image-64" title="cakes" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/cakes.jpg" alt="Some cakes waiting to be judged" width="202" height="134">',
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 6,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Arts & Crafts',
                'number' => '7',
                'notes' => NULL,
                'judges' => 'Mrs C. Tudway & Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-66" title="Cushion" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/Cushion.jpg" alt="A prize-winning cushion" width="200" height="300">',
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Floral, Fruit & Vegetables',
                'number' => '8',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey and Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-68" title="wildlife garden" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/wildlife-garden.jpg" alt="A junior wildlife garden" width="300" height="200">',
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Cookery, Arts & Crafts',
                'number' => '9',
                'notes' => NULL,
                'judges' => 'Mr Rounce, Mr Bailey, Mr Kimbell, Mrs Tudway, Mrs Edwards &  Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-70" title="junior cookery" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/junior-cookery.jpg" alt="Miscellaneous winning junior cookery prizes" width="300" height="200">',
                'show_id' => 2,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Novices',
                'number' => '1',
                'notes' => 'Entry to this novice class is open to members who have not won a prize in any previous Petersham Flower Show',
                'judges' => 'Mr R. Bailey & Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Flowers',
                'number' => '2',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => '<img class="alignleft size-full wp-image-62" title="Winning Rose" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/WinningRose.jpg" alt="A winning rose in our Flowers section" width="225" height="300">',
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Fruit',
                'number' => '3',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 3,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Vegetables & Produce',
                'number' => '4',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-63" title="judging vegetables" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/judging-vegetables.jpg" alt="Image of Mr Studman judging vegetables" width="200" height="300">',
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 2,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Floral Arrangement',
                'number' => '5',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => NULL,
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 5,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Cookery',
                'number' => '6',
                'notes' => NULL,
                'judges' => 'Mr J. Rounce',
                'image' => '<img class="alignleft size-full wp-image-64" title="cakes" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/cakes.jpg" alt="Some cakes waiting to be judged" width="202" height="134">',
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 6,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Arts & Crafts',
                'number' => '7',
                'notes' => NULL,
                'judges' => 'Mrs C. Tudway & Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-66" title="Cushion" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/Cushion.jpg" alt="A prize-winning cushion" width="200" height="300">',
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Floral, Fruit & Vegetables',
                'number' => '8',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey and Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-68" title="wildlife garden" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/wildlife-garden.jpg" alt="A junior wildlife garden" width="300" height="200">',
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Cookery, Arts & Crafts',
                'number' => '9',
                'notes' => NULL,
                'judges' => 'Mr Rounce, Mr Bailey, Mr Kimbell, Mrs Tudway, Mrs Edwards &  Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-70" title="junior cookery" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/junior-cookery.jpg" alt="Miscellaneous winning junior cookery prizes" width="300" height="200">',
                'show_id' => 3,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Novices',
                'number' => '1',
                'notes' => 'Entry to this novice class is open to members who have not won a prize in any previous Petersham Flower Show',
                'judges' => 'Mr R. Bailey & Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Flowers',
                'number' => '2',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => '<img class="alignleft size-full wp-image-62" title="Winning Rose" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/WinningRose.jpg" alt="A winning rose in our Flowers section" width="225" height="300">',
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Fruit',
                'number' => '3',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 3,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Vegetables & Produce',
                'number' => '4',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-63" title="judging vegetables" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/judging-vegetables.jpg" alt="Image of Mr Studman judging vegetables" width="200" height="300">',
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 2,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Floral Arrangement',
                'number' => '5',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => NULL,
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 5,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Cookery',
                'number' => '6',
                'notes' => NULL,
                'judges' => 'Mr J. Rounce',
                'image' => '<img class="alignleft size-full wp-image-64" title="cakes" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/cakes.jpg" alt="Some cakes waiting to be judged" width="202" height="134">',
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 6,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Arts & Crafts',
                'number' => '7',
                'notes' => NULL,
                'judges' => 'Mrs C. Tudway & Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-66" title="Cushion" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/Cushion.jpg" alt="A prize-winning cushion" width="200" height="300">',
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Floral, Fruit & Vegetables',
                'number' => '8',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey and Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-68" title="wildlife garden" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/wildlife-garden.jpg" alt="A junior wildlife garden" width="300" height="200">',
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Cookery, Arts & Crafts',
                'number' => '9',
                'notes' => NULL,
                'judges' => 'Mr Rounce, Mr Bailey, Mr Kimbell, Mrs Tudway, Mrs Edwards &  Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-70" title="junior cookery" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/junior-cookery.jpg" alt="Miscellaneous winning junior cookery prizes" width="300" height="200">',
                'show_id' => 5,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Novices',
                'number' => '1',
                'notes' => 'Entry to this novice class is open to members who have not won a prize in any previous Petersham Flower Show',
                'judges' => 'Mr R. Bailey & Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Flowers',
                'number' => '2',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => '<img class="alignleft size-full wp-image-62" title="Winning Rose" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/WinningRose.jpg" alt="A winning rose in our Flowers section" width="225" height="300">',
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 1,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Fruit',
                'number' => '3',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:15',
                'updated_at' => '2024-03-25 22:30:15',
                'is_junior' => 0,
                'judge_role_id' => 3,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Vegetables & Produce',
                'number' => '4',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-63" title="judging vegetables" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/judging-vegetables.jpg" alt="Image of Mr Studman judging vegetables" width="200" height="300">',
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 2,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Floral Arrangement',
                'number' => '5',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => NULL,
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 5,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Cookery',
                'number' => '6',
                'notes' => NULL,
                'judges' => 'Mr J. Rounce',
                'image' => '<img class="alignleft size-full wp-image-64" title="cakes" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/cakes.jpg" alt="Some cakes waiting to be judged" width="202" height="134">',
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 6,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Arts & Crafts',
                'number' => '7',
                'notes' => NULL,
                'judges' => 'Mrs C. Tudway & Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-66" title="Cushion" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/Cushion.jpg" alt="A prize-winning cushion" width="200" height="300">',
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Floral, Fruit & Vegetables',
                'number' => '8',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey and Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-68" title="wildlife garden" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/wildlife-garden.jpg" alt="A junior wildlife garden" width="300" height="200">',
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Cookery, Arts & Crafts',
                'number' => '9',
                'notes' => NULL,
                'judges' => 'Mr Rounce, Mr Bailey, Mr Kimbell, Mrs Tudway, Mrs Edwards &  Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-70" title="junior cookery" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/junior-cookery.jpg" alt="Miscellaneous winning junior cookery prizes" width="300" height="200">',
                'show_id' => 6,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Novices',
                'number' => '1',
                'notes' => 'Entry to this novice class is open to members who have not won a prize in any previous Petersham Flower Show',
                'judges' => 'Mr R. Bailey & Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Flowers',
                'number' => '2',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => '<img class="alignleft size-full wp-image-62" title="Winning Rose" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/WinningRose.jpg" alt="A winning rose in our Flowers section" width="225" height="300">',
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 1,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Fruit',
                'number' => '3',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 3,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Vegetables & Produce',
                'number' => '4',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-63" title="judging vegetables" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/judging-vegetables.jpg" alt="Image of Mr Studman judging vegetables" width="200" height="300">',
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 2,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Floral Arrangement',
                'number' => '5',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => NULL,
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 5,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Cookery',
                'number' => '6',
                'notes' => NULL,
                'judges' => 'Mr J. Rounce',
                'image' => '<img class="alignleft size-full wp-image-64" title="cakes" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/cakes.jpg" alt="Some cakes waiting to be judged" width="202" height="134">',
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 6,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Arts & Crafts',
                'number' => '7',
                'notes' => NULL,
                'judges' => 'Mrs C. Tudway & Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-66" title="Cushion" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/Cushion.jpg" alt="A prize-winning cushion" width="200" height="300">',
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Floral, Fruit & Vegetables',
                'number' => '8',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey and Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-68" title="wildlife garden" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/wildlife-garden.jpg" alt="A junior wildlife garden" width="300" height="200">',
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Cookery, Arts & Crafts',
                'number' => '9',
                'notes' => NULL,
                'judges' => 'Mr Rounce, Mr Bailey, Mr Kimbell, Mrs Tudway, Mrs Edwards &  Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-70" title="junior cookery" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/junior-cookery.jpg" alt="Miscellaneous winning junior cookery prizes" width="300" height="200">',
                'show_id' => 9,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Novices',
                'number' => '1',
                'notes' => 'Entry to this novice class is open to members who have not won a prize in any previous Petersham Flower Show',
                'judges' => 'Mr R. Bailey & Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Flowers',
                'number' => '2',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => '<img class="alignleft size-full wp-image-62" title="Winning Rose" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/WinningRose.jpg" alt="A winning rose in our Flowers section" width="225" height="300">',
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 1,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Fruit',
                'number' => '3',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => NULL,
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 3,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Vegetables & Produce',
                'number' => '4',
                'notes' => NULL,
                'judges' => 'Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-63" title="judging vegetables" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/judging-vegetables.jpg" alt="Image of Mr Studman judging vegetables" width="200" height="300">',
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 2,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Floral Arrangement',
                'number' => '5',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey',
                'image' => NULL,
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 5,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Cookery',
                'number' => '6',
                'notes' => NULL,
                'judges' => 'Mr J. Rounce',
                'image' => '<img class="alignleft size-full wp-image-64" title="cakes" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/cakes.jpg" alt="Some cakes waiting to be judged" width="202" height="134">',
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => 6,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Arts & Crafts',
                'number' => '7',
                'notes' => NULL,
                'judges' => 'Mrs C. Tudway & Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-66" title="Cushion" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/Cushion.jpg" alt="A prize-winning cushion" width="200" height="300">',
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 0,
                'judge_role_id' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Floral, Fruit & Vegetables',
                'number' => '8',
                'notes' => NULL,
                'judges' => 'Mr R. Bailey and Mrs P. Edwards',
                'image' => '<img class="alignleft size-full wp-image-68" title="wildlife garden" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/wildlife-garden.jpg" alt="A junior wildlife garden" width="300" height="200">',
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Cookery, Arts & Crafts',
                'number' => '9',
                'notes' => NULL,
                'judges' => 'Mr Rounce, Mr Bailey, Mr Kimbell, Mrs Tudway, Mrs Edwards &  Mr C Bayne',
                'image' => '<img class="alignleft size-full wp-image-70" title="junior cookery" src="http://www.petershamhorticulturalsociety.org.uk/wp-content/uploads/2012/03/junior-cookery.jpg" alt="Miscellaneous winning junior cookery prizes" width="300" height="200">',
                'show_id' => 8,
                'created_at' => '2024-03-25 22:30:16',
                'updated_at' => '2024-03-25 22:30:16',
                'is_junior' => 1,
                'judge_role_id' => NULL,
            ),
        ));
        
        
    }
}