version: '3.1'

services:
  web:
    image: nginx:latest
    ports:
      - "3008:80"
    volumes:
      - .:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - app
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
#      - ./docker/php/etc:/usr/local/etc/php
    depends_on:
      - db
    ports:
      - "9210:9000"
  db:
    image: mariadb:10.3.13
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=flowers
      - MYSQL_USER=flowers
      - MYSQL_PASSWORD=Flowersaregreat1!
    ports:
      - "30396:3306"
    volumes:
      - .:/var/www/html
      - flowersdata:/var/lib/mysql
volumes:
  flowersdata:
